# Generated by Django 3.2 on 2025-05-10 22:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('annotation_ratio', models.FloatField(null=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PictureSlices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('picture_file', models.FileField(upload_to='pictures', verbose_name='Picture file')),
                ('stud_group_id', models.CharField(max_length=120)),
                ('author_id', models.CharField(max_length=120)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date created')),
                ('study_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date created')),
                ('picture_file', models.FileField(upload_to='pictures', verbose_name='Picture file')),
                ('annotation_num', models.IntegerField(default=0)),
                ('study_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('user_id', models.CharField(max_length=120)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('annotated_picture', models.FileField(null=True, upload_to='annotated_pictures', verbose_name='Annotated picture')),
                ('annotator', models.CharField(default='', max_length=50)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date created')),
                ('aligned_label', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('align', models.IntegerField(default=0)),
                ('confirm', models.IntegerField(default=0)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.picture')),
            ],
        ),
    ]
