# Generated by Django 3.2 on 2025-05-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20250511_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='annotation_ratio',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
