# Generated by Django 3.2 on 2025-05-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20250511_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pictureslices',
            name='picture_file',
        ),
        migrations.RemoveField(
            model_name='pictureslices',
            name='stud_group_id',
        ),
        migrations.RemoveField(
            model_name='pictureslices',
            name='study_group',
        ),
        migrations.AddField(
            model_name='pictureslices',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.annotation'),
        ),
    ]
