# Generated by Django 3.2 on 2025-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20250515_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='study_group',
        ),
        migrations.AddField(
            model_name='picture',
            name='study_group_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
