# Generated by Django 3.2 on 2025-05-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20250515_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
