# Generated by Django 3.2 on 2025-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_studygroup_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notices',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='notices',
            name='status',
            field=models.CharField(default='系统消息', max_length=120),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
