# Generated by Django 3.2 on 2025-05-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20250516_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_confirm',
            field=models.BooleanField(default=True),
        ),
    ]
