# Generated by Django 3.2 on 2025-05-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_picture_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='target',
            field=models.CharField(default='', max_length=50),
        ),
    ]
