# Generated by Django 3.2 on 2025-05-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_annotation_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotated_picture',
        ),
        migrations.AddField(
            model_name='annotation',
            name='align_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
