# Generated by Django 3.2 on 2025-05-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20250517_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label_id',
            field=models.IntegerField(default=0),
        ),
    ]
