# Generated by Django 3.2 on 2025-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20250517_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='color',
            field=models.CharField(default='#1D8CF8', max_length=50),
        ),
    ]
