# Generated by Django 3.2 on 2025-05-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_annotation_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureslices',
            name='author_id',
        ),
        migrations.AddField(
            model_name='pictureslices',
            name='group',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pictureslices',
            name='label',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pictureslices',
            name='pic',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='color',
            field=models.CharField(default='# 1D8CF8', max_length=50),
        ),
        migrations.AlterField(
            model_name='pictureslices',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
