# Generated by Django 3.2 on 2025-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_annotation_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='isDef',
            field=models.IntegerField(default=0),
        ),
    ]
