# Generated by Django 3.2 on 2025-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_label_isdef'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pictureslices',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
