# Generated by Django 3.2 on 2025-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20250521_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureslices',
            name='annotator',
            field=models.CharField(default='', max_length=50),
        ),
    ]
